### PR TITLE
Export New-GPRegistryPolicy

### PR DESCRIPTION
**Pull request by shubhamgupta514**
Export New-GPRegistryPolicy  in order to create GPRegistryPolicy instances for other cmdlets

### CODE REVIEW

**Comment by shubhamgupta514** [comment]
@zjalali Could you please review and merge this pull request

**Comment by God-damnit-all** [comment]
Looks like you submitted this with the wrong line endings: https://github.com/PowerShell/GPRegistryPolicy/pull/10/commits/f71d96e5b64b8a7f18b131783c634f002bb55b39

**Comment by shubhamgupta514** [comment]
> Looks like you submitted this with the wrong line endings: [f71d96e](https://github.com/PowerShell/GPRegistryPolicy/commit/f71d96e5b64b8a7f18b131783c634f002bb55b39)

I have made changes only in the last line of the file i.e.

Export-ModuleMember -Function 'Import-GPRegistryPolicy','Export-GPRegistryPolicy','Test-GPRegistryPolicy','Parse-PolFile','Read-RegistryPolicies','Create-RegistrySettingsEntry','Create-GPRegistryPolicyFile','Append-RegistryPolicies','New-GPRegistryPolicy'

**Comment by God-damnit-all** [comment]
Yes, but the line endings got messed up. It's making github think you're deleting every single line of the file and adding every single line of the file.

**Comment by shubhamgupta514** [comment]
I am closing this pull request and creating a new one

**Pull request closed without merging**
